blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()) ,
    path("<int:pk>/", views.PostDetail.as_view()),
    path("category/<str:slug>/", views.category_page),
    path("tag/<str:slug>/", views.tag_page),
    path("create_post/", views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path("<int:pk>/new_comment/", views.new_comment),
    path("update_comment/<int:pk>/", views.CommentUpdate.as_view()),
    path("delete_comment/<int:pk>/", views.delete_comment), 
    
    # path("recipecc/<int:recipe_num>/", views.recipecc),
]

ingredients/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.post_list, name='ingredients'),
    # path("upload_image/", views.upload_image, name='upload_image'),
    # path("upload_text/", views.upload_text, name='upload_text'),
    path("upload_text/", views.UploadText.as_view(), name='upload_text'),
    path('upload_image/',views.MnistImageCreate.as_view(), name='upload_image'),
    path('image_result/<int:pk>/',views.image_result),
    # path('recipe_list/',views.RecipeListView.as_view()),
    path('recipe_list/',views.recommend,name='recipe_list'),
    path('delete_all/', views.delete_all),
    path('recipe/',views.recommend_all, name='recipe_list_all'),
    path('user_recipe/<int:pk>/',views.RecipePostDetail.as_view()),
    path('user_recipe/<int:pk>/new_comment/',views.new_comment),
    path("user_recipe/delete_comment/<int:pk>/", views.delete_comment), 
    path('user_recipe/',views.RecipePostList.as_view()),
    path('user_recipe/category/<str:slug>/',views.category_page),
    path('tag/<str:slug>/',views.tag_page),
    path('user_recipe/create_post/',views.RecipePostCreate.as_view()),
    path('user_recipe/update_post/<int:pk>/',views.RecipePostUpdate.as_view()),
    path("user_recipe/update_comment/<int:pk>/", views.CommentUpdate.as_view()),
    path('use_all/', views.use_all),
    path('trash_all/', views.trash_all),
    path('mypage/', views.UseTrashIView),
]

project03_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("ingredients/", include('ingredients.urls')),
    path('', include('single_pages.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ingredients/models.py
from django.db import models
from django.contrib.auth.models import User
import os

class Ingredients(models.Model):
    ingredient = models.CharField(max_length=20)
    expiration_date = models.DateField(blank=True, null = True)    # 유통기한
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    isDone = models.CharField(max_length=2,blank=True, null = True)
    updated_at = models.DateTimeField(auto_now=True)
    # head_image = models.ImageField(upload_to='ingredients/images/%Y/%m/%d/')
    
    def __str__(self):
        return f'[{self.pk}] {self.ingredient}'
    
    def get_absolute_url(self):
        return f'/ingredients/'

class MnistImage(models.Model):
    head_image = models.ImageField(upload_to='ingredients/images/%Y/%m/%d/')
    result = models.CharField(max_length=30,blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    expiration_date = models.DateField(blank=True, null = True)
    isDone = models.CharField(max_length=2,blank=True, null = True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.id}] {self.result}'

    def get_absolute_url(self):
        return f'/ingredients/image_result/{self.pk}/'

class RecipeList(models.Model):
    class DiffChoices(models.TextChoices):
        아무나 = '아무나'
        초급 = '초급'
        중급 = '중급'
        고급 = '고급'
        신 = '신의경지'
    class TimeChoices(models.TextChoices):
        오분 = '5분이내'
        십분 = '10분이내'
        십오분 = '15분이내'
        삼십분 = '30분이내'
        한시간 = '60분이내'
        한시간반 = '90분이내'
        두시간 = '2시간이내'
        두시간이상 = '2시간이상'
        
    rc_num = models.IntegerField(blank=True, null=True)
    rc_name = models.CharField(max_length=100, blank=True, null=True)
    rc_view = models.IntegerField(blank=True, null=True)
    rc_rec = models.IntegerField(blank=True, null=True)
    rc_scrap = models.IntegerField(blank=True, null=True)
    rc_type = models.CharField(max_length=100, blank=True, null=True)
    rc_sit = models.CharField(max_length=100, blank=True, null=True)
    rc_sort = models.CharField(max_length=100, blank=True, null=True)
    rc_nick = models.CharField(max_length=100, blank=True, null=True)
    rc_info = models.CharField(max_length=100, blank=True, null=True)
    rc_ing = models.CharField(max_length=200, blank=True, null=True)
    rc_diff = models.CharField(max_length=100, blank=True, null=True, choices=DiffChoices.choices)
    rc_time = models.CharField(max_length=100, blank=True, null=True, choices=TimeChoices.choices)
    rc_src = models.CharField(max_length=200, blank=True, null=True)
    # author = models.ForeignKey("Author", on_delete=models.CASCADE)

###### 태그
class Tags(models.Model): # models의 Model을 상속받아야 함
    ### 필요한 필드 정의(pk는 알아서 되니까 제외)
    name = models.CharField(max_length=50)
    # unique=True : 똑같은 데이터는 못 들어감
    # name을 그대로 url에 사용하면 특수문자 등으로 문제 발생할 수 있음
    # slug 사용
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    # name에 사용된 특수문자 등으로 url에 사용하지 못하면 바꿔서 처리, 유니코드 허용  
    # slug에만 unique=True 적용해도 됨
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/ingredients/tag/{self.slug}/'
    

###### 카테고리
class Categories(models.Model): # models의 Model을 상속받아야 함
    ### 필요한 필드 정의(pk는 알아서 되니까 제외)
    name = models.CharField(max_length=50, unique=True)
    # unique=True : 똑같은 데이터는 못 들어감
    # name을 그대로 url에 사용하면 특수문자 등으로 문제 발생할 수 있음
    # slug 사용
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    # name에 사용된 특수문자 등으로 url에 사용하지 못하면 바꿔서 처리, 유니코드 허용  
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/ingredients/category/{self.slug}/'
    
    class Meta:
        verbose_name_plural = "Categories"
    


class RecipePost(models.Model): 
    ### 제목 
    title = models.CharField(max_length=30)# CharField() : 한 줄짜리 문자 필드, 최대 30
    # 모델이 어떻게 만들어져야 하는지를 부모로 부터 상속받음
    # pk는 알아서 만들어줌(우리가 지정 안해도 됨)
    recommend = models.IntegerField(blank=True, null=True)
    hook_text = models.CharField(max_length=100, blank=True) 
    content = models.TextField() 
    head_image = models.ImageField(upload_to='ingredients/images/%Y/%m/%d/', blank=True)    
    ingredient = models.CharField(max_length=200, blank=True, null=True)
    category = models.ForeignKey(Categories, null=True, blank=True, on_delete=models.SET_NULL, related_name='category')
    time = models.CharField(max_length=100, blank=True, null=True)
    # category_time = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tags,null=True,blank=True)
    
    ### 아이디와 제목 표시
    def __str__(self): # class 인자는 무조건 자기자신(self)?
        return f'[{self.id}] {self.title} :: {self.author}' # [글번호]
    # 함수 추가 -> migration 안 해도 됨
    
    def get_absolute_url(self):
        return f'/ingredients/user_recipe/{self.pk}/'  # blog/pk값 들어가게
    
    # def get_file_name(self):
    #     return os.path.basename(self.file_upload.name) # basename 파일명만 return시켜줌
    
    # def get_file_ext(self):
    #     return self.get_file_name().split('.')[-1] 
    # 확장자를 포함한 파일명을 '.'을 기준으로 잘라서 뒤의 것(확장자) 사용
    # 확장자를 가져올 때 1이 아닌 -1로 맨 마지막에 있는 것을 가져오는 게 정확함
    # 함수는 makemigration - migrate할 필요 없음
    
class Comment(models.Model):
    post = models.ForeignKey(RecipePost, on_delete=models.CASCADE, related_name='post')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.author}::{self.content}'
    
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/1330/12d7c1cea8718f2e/svg/{self.author.email}'
        
class MonthlyWeatherByCity(models.Model):
    month = models.IntegerField()
    boston_temp = models.DecimalField(max_digits=5, decimal_places=1)
    houston_temp = models.DecimalField(max_digits=5, decimal_places=1)

ingredients/forms.py
from django import forms 
from .models import Ingredients
from .models import Comment

class TextForm(forms.ModelForm):
    class Meta:
        model=Ingredients
        fields=['ingredient','expiration_date']
        labels = {
            'ingredient': '재료명',
            'expiration_date': '유통기한',
        }  
        
class RecipeListFilterForm(forms.Form):
    name = forms.CharField()
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

ingredients/templates/ingredients/Ingredients_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}텍스트입력{% endblock %}
{%block main_area%}

<body style="padding-top: 150px;">
    <div class="container">
        <h1>텍스트로 입력하기</h1>
        <hr />
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/ingredients">나의 냉장고</a></li>
            <li class="breadcrumb-item active">텍스트로 입력</li>
        </ol>
        <br>
        <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form|crispy}}
            <br>
            <div class="text-end mb-3">
                <button type="submit" class="btn btn-primary">저장</button>
            </div>
        </form>
    </div>
</body>
{%endblock%}

ingredients/templates/ingredients/MnistImage_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}이미지입력{% endblock %}
{% block main_area %}

<body style="padding-top: 150px;">
    <div class="container">
        <h1>이미지로 입력하기</h1>
        <hr />
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/ingredients">나의 냉장고</a></li>
            <li class="breadcrumb-item active">이미지로 입력</li>
        </ol>
        <br>
        <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form|crispy}}
            <br>
            <div class="text-end mb-3">
                <button type="submit" class="btn btn-primary">이미지검색</button>
            </div>
        </form>
    </div>
</body>
{%endblock%}

ingredients/templates/ingredients/comment_form.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}코멘트{% endblock %}
{% block main_area %}
<body style="padding-top: 100px;">
    <h1>코멘트</h1>
    <hr/>
    <form method="Post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-primary float-right">제출</button>
    </form>
</body>
{% endblock %}

ingredients/templates/ingredients/recipe_all.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_title %}레시피 목록{% endblock %}
{% block main_area %}

<style>
  div.minjun {
    border: 1px solid #bcbcbc;
  }
  table.minjun {
    width: 1100px;
  }
  th.minjun, td.minjun {
    width: 150px;

  }
  th.minjun1, td.minjun1 {
    width: 200px;

  }
  th.minjun2, td.minjun2 {
    width: 750px;

  }
  th.minjun3, td.minjun3 {
    width: 90px;

  }

</style>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <!-- <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" /> -->

    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<body style="padding-top: 100px;">
    <!-- Featured blog post-->
    <div class="container">
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid col-lg-12">

                    <div class="container-fluid px-4">
                        <br>
                        <h1 class="mt-4">전체 레시피</h1>
                        <!-- <hr /> -->
                        <!-- <h1 class="fw-bold text-black m-0 nav2 mt-4">요리조리</h1> -->
                        </a>
                        <hr />
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="/ingredients">나의 냉장고</a></li>
                            <li class="breadcrumb-item active">전체 레시피</li>
                        </ol>
 
                        <!-- <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <div class="mb-3">

                                </div>
                            </div> -->
                        <br>
                        <div class="col col-xxl-12 card mb-4">
                            <div class="card-header">
                                <i class="fa-solid fa-utensils"></i>
                                레시피 목록
                            </div>
                            
                            <div class="card-body minjun">
                                <table class="minjun" id="datatablesSimple">
                                    <form method="GET" action="{% url 'recipe_list_all' %}">
                                        {{ form.as_p }}
                                        <input type="submit" value="Submit" class="btn btn-primary" />
                                    </form>
                                    <hr/>
                                    <thead>
                                        <tr>
                                            <th class="text-center minjun">레시피<br>바로가기</th>
                                            <th class="text-center minjun1">요리명</th>
                                            <th class="text-center minjun">난이도</th>
                                            <th class="text-center minjun">소요시간</th>
                                            <th class="text-center minjun2">재료</th>
                                            <th class="text-center minjun3">추천수</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th class="text-center minjun">레시피<br>바로가기</th>
                                            <th class="text-center minjun1">요리명</th>
                                            <th class="text-center minjun">난이도</th>
                                            <th class="text-center minjun">소요시간</th>
                                            <th class="text-center minjun2">재료</th>
                                            <th class="text-center minjun3">추천수</th>
                                        </tr>
                                    </tfoot>
                                    <tbody id="tbody">
                                        <!-- <div>
                                            <form method="get">
                                                {{ listing_filter.form|crispy }}
                                                <button class="btn btn-sm btn-danger" type="submit">Submit</button>
                                            </form>
                                        </div> -->
                                        <!-- {% for listing in listing_filter.qs %}
                                            <div class = "col">
                                                {% include "ingredients/recipe_all.html" %}
                                            </div>
                                        {% endfor %} -->
                                        {% for p in recipe_list %}
                    
                                        <tr class="fs-7">
                                            <td class="text-center minjun"><a role="button" class="btm_image" id="img_btn" href="https://www.10000recipe.com/recipe/{{ p.rc_num }}">
                                                    <!-- <img src="{% static 'img/icon1.png' %}" width="30" height="30"></a></td> -->
                                                    <img src="{{ p.rc_src }}" width="50" height="50"></a></td>
                                            <td class="text-center minjun1">
                                                <p class="fw-bold fs-8">{{ p.rc_name }}</p>
                                            </td>
                                            <td class="text-center minjun">{{ p.get_rc_diff_display }}</td>
                                            <td class="text-center minjun">{{ p.get_rc_time_display }}</td>
                                            <td align="left" class="minjun2">{{ p.rc_ing }}</td>
                                            <td class="text-center minjun3">{{ p.rc_rec }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <br>

    <!-- 페이지네이션 -->
    {% if is_paginated %}
    <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    
    <!-- <script src="{% static 'js/datatables-simple-demo.js' %}"></script>문제가 되는 js... -->
    <!-- <script type="text/javascript" src="/js/common/jquery/prototype.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    
    

</body>
{% endblock %}

ingredients/templates/ingredients/recipepost_detail.html
{%extends 'blog/base.html'%}
<!--base 상속받기, 템플릿 기준으로 경로-->
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% block head_title %}레시피 커뮤니티{% endblock %}
{% block main_area %}


<!-- Post content-->

<body style="padding-top: 200px;">
    <div class="container">
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/ingredients/user_recipe/">참여 레시피</a></li>
            <li class="breadcrumb-item active">{{ recipepost.title }}</li>
        </ol>
            <!-- Post header-->
        <header class="mb-4">
            <!-- edit button-->
            {%if user.is_authenticated and user == recipepost.author%}
                <div class="text-end">
                    <a role="button" class="btn btn-secondary btn-sm"
                        href="/ingredients/user_recipe/update_post/{{recipepost.pk}}/">
                        <i class="fa-solid fa-eraser"></i> 수정
                    </a>
                </div>
            {%endif%}
            <!-- 제목 Post title-->
            <h1 class="fw-bolder mb-1">{{ recipepost.title }}</h1>
            <!--모델명.title-->
            {%if recipepost.hook_text %}
                <h5 class="text-muted">{{ recipepost.hook_text }}</h5>
            {%endif%}
            <!-- 작성일자 Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ recipepost.created_at }} by
                {{ recipepost.author|upper }}</div>
            <!-- Post categories-->
            {%if recipepost.category %}
                <div class="text-start"><span class="badge text-bg-secondary">{{ recipepost.category }}</span></div>
            {%else%}
                <div class="text-start"><span class="badge text-bg-secondary">미분류</span></div>
            {%endif%}
        </header>
        <!-- Preview image figure-->
        <section class="mb-5">
            <figure class="mb-4">
                {%if recipepost.head_image %}
                    <img class="img-fluid" src="{{ recipepost.head_image.url }}" alt="..." />
                {%else%}
                    <img class="img-fluid" src="https://picsum.photos/seed/{{recipepost.id}}/900/400" alt="..." />
                {%endif%}
            </figure>
            <!-- 본문 Post content-->
            <div>
                <p class="fs-5 mb-4"><i class="fa-solid fa-utensils"></i> 요리재료 : {{ recipepost.ingredient }}</p>
                <p class="fs-5 mb-4">{{ recipepost.content }}</p>
                {% if recipepost.tags.exists %}
                    <div class="mb-3">
                        <!-- 간격주기 -->
                        <i class="fa-solid fa-hashtag"></i>
                        <!--ㄴ폰트어썸 아이콘-->
                        {%for tag in recipepost.tags.iterator%}
                            <a href="{{tag.get_absolute_url}}">
                                <span class=" badge text-bg-light">{{tag}}</span>
                                <!--ㄴ부트스트랩-->
                            </a>
                        {%endfor%}
                    </div>
                {%endif%}
            </div>
        </section>
        <!-- Comments section-->
        <section class="mb-5 bg-white">
            <div class="card mb-4" id='comment-area'>
                <div class="card-body">
                    <!-- Comment form-->
                    {% if user.is_authenticated %}
                        <form class="mb-1" id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                            {% csrf_token %}
                            <div class="form-group mb-2">
                                {{ comment_form | crispy }}
                            </div>
                            <button type="submit" class="btn btn-primary">제출</button>
                        </form>
                    {% else %}
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-bs-toglle="modal"
                            data-bs-target="#loginModal">로그인 후 작성</a>
                    {% endif %}
                </div>
            </div> 
            {% if recipepost.comment_set.exists %}
                {% for comment in recipepost.comment_set.iterator %}
                <!-- Single comment-->
                    <div class="container bg-light">
                        <div class="media mb-4" id="comment-{{ comment.pk }}">
                            <img class="d-flex mr-3 rounded-circle" src="{{ comment.get_avatar_url }}"
                                alt="{{ comment.author }}" width="40px">
                            <div class="media-body">
                                <h5 class="mt-0">{{ comment.author.username }} &nbsp;&nbsp;
                                    <small class="text-muted fs-6">{{ comment.created_at }}</small>
                                </h5>
                                <p>{{ comment.content | linebreaks }}</p>
                                {% if user.is_authenticated and comment.author == user %}
                                    <div class="float-right">
                                        <a role="button" class="btn btn-sm btn-info " id="comment-{{ comment.pk }}-update-btn"
                                            href="/ingredients/update_comment/{{ comment.pk }}">
                                            수정
                                        </a>
                                        <a role="button" class="btn btn-sm btn-danger"
                                            id="comment-{{ comment.pk }}-delete-modal-btn" data-toggle="modal"
                                            data-target="#deleteCommentModal-{{ comment.pk }}" href="#">
                                            삭제
                                        </a>
                                    </div>
                                    <!-- Modal -->
                                    <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog"
                                        aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">삭제하시겠습니까?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <del>{{ comment | linebreaks }}</del>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                                                    <a role="button" class="btn btn-danger"
                                                        href="/ingredients/delete_comment/{{ comment.pk }}/">삭제</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if comment.created_at != comment.modified_at %}
                                    <p class="text-muted float-right"><small>수정: {{ comment.modified_at }}</small></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </section>
    </div>
</body>
<!-- Modal start-->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="loginModalLabel">로그인</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 col-sm-12 d-grid gap-2">
                        <a role="button" class="btn btn-outline-dark btn-sm" href="{% provider_login_url 'google' %}">
                            <i class="fa-brands fa-google"></i> 구글로 로그인</a>
                        <a role="button" class="btn btn-outline-dark btn-sm" href="/accounts/login/">
                            <i class="fa-solid fa-user-plus"></i> Login in with username</a>
                    </div>
                    <div class="col-md-6 col-sm-12 d-grid gap-2">
                        <a role="button" class="btn btn-outline-dark btn-sm" href="#">
                            <i class="fa-solid fa-n"></i> 네이버로 로그인</a>
                        <a role="button" class="btn btn-outline-dark btn-sm" href="/accounts/signup/">
                            <i class="fa-regular fa-envelope"></i> 이메일주소로 로그인</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal end -->
{%endblock%}

ingredients/templates/ingredients/recipepost_form.html
{%extends 'blog/base.html'%}
{% block head_title %}레시피 작성{% endblock %}
{%block main_area%}
<body style="padding-top: 200px;">
<div class="container">
<h1>레시피 작성</h1>
<hr />
<form method="post" enctype="multipart/form-data">
    {%csrf_token%} <!-- form 태그 안에 무조건 적고 시작, csrf 공격에서 보호 위함-->
    <table>
        {{form}} <!-- views에 정의된 필드명 보고 알아서 만들어줌--> 
        <!-- action을 장고에서 알아서 처리해줌 -->
        <tr>
            <th><label for="id_tags_str">태그:</label></th>
            <td><input type="text" name="tags_str" id="id_tags_str"></td> <!--Tags: 눌러도 커서가 -->
        </tr>
    </table>
    <div class="text-end mb-3">
    <button type="submit" class="btn btn-primary">제출</button>
    </div>
</form>
</div>
</body>
{%endblock%}

ingredients/templates/ingredients/recipepost_update_form.html
{%extends 'blog/base.html'%}
{% block head_title %}레시피 커뮤니티{% endblock %}
{%block main_area%}

<body style="padding-top: 150px;">
    <div class="container">
        <h1>수정</h1>
        <hr />
        <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <!-- form 태그 안에 무조건 적고 시작, csrf 공격에서 보호 위함-->
            <table>
                {{form}}
                <!-- views에 정의된 필드명 보고 알아서 만들어줌-->
                <!-- action을 장고에서 알아서 처리해줌 -->
                <tr>
                    <th><label for="id_tags_str">태그:</label></th>
                    <td><input type="text" name="tags_str" id="id_tags_str" value="{{tags_str_default}}"> </td>
                        <!--Tags: 눌러도 커서가 -->
                </tr>
            </table>
            <div class="text-end mb-3">
                <button type="submit" class="btn btn-primary">제출</button>
            </div>
        </form>
    </div>
</body>
{%endblock%}